export const BASE_URL = 'https://fashion-leo.servepratham.com/api/v2/'



export const endpoint = {
    getCart: 'user/cart/save',
    createOrder: 'user/order/create',
    checkOut: 'user/order/checkout',
    getHistory: 'user/order/historyByOrder',
    getTopProducts: 'user/sorting/top-product/most-popular',
    getTrendingProduct: 'user/sorting/featured-product/most-popular',
    login: 'login',
    getCategory: 'user/getcategory',
    getFeatureProduct: 'user/sorting/featured-product',
    getByVendor: 'user/nearBy/vendors',
    getNewArivals: 'user/sorting/recent-product/new-arrivals',
    getslidingBanner: "user/slider",
    singUp: 'user-signup',
    VerifyOtp: 'otp/verify',
    cart: 'user/cart/list',
    wishlist: 'user/add/wishlist',
    getWishlist: "user/myWishlist",
    HomePage: 'user/homepage',
    myProfile: 'user/myProfile',
    profileUpdate: 'user/profileUpdate',
    updateRequest: 'user/update-request',
    updateotp: 'user/update-request/otp',
    userPasswordChange: 'user/password-change',
    getAllAddress: 'user/address/get-all-address',
    addNewAddress: 'user/address/save',
    getBankDetail: 'user/bank-details',
    addBankDetail: 'user/add-bank-details',
    followVendor: "user/follow",
    productByCategort: 'user/category/product',
    deleteAddress: 'user/address/remove/',
    updateAddress: 'user/address/update',
    getByVendorId: 'user/vendorById',
    removeCart: 'user/cart/remove',
    cartItemCount: "user/cart/item-count",
    LoginWithEmail: 'login-with-password',
    get_coupon_code: 'user/coupon/get-coupon-code',
    apply_coupon: "user/coupon/apply-coupon-code",
    myNotification: 'user/customer/myNotifications',
    currency: 'currency',
    readNotification: 'user/customer/readNotifications',
    productById: 'user/productById',
    deleteAccount: 'user/delete-account',
    check_courier_service: 'check-courier-service',
    OrderDetailbyid: 'user/order/order-Details-By',
    order_cancel: 'user/order/cancel',
    search_product: 'user/globalSearch',
    item_count: 'user/cart/item-count',
    cms: 'user/cms',
    myFollowings: 'user/myFollowings'
}
